services:
  rnsd:
    hostname: rnsd
    image: ghcr.io/greymesa/reticulum:latest
    networks:
      reticulum:
        ipv4_address: 172.18.0.2
    volumes:
      - rnsd-config:/config

  lxmd:
    hostname: lxmd
    image: ghcr.io/greymesa/reticulum:lxmd
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - lxmd-config:/config

  echobot:
    hostname: echobot
    image: ghcr.io/greymesa/reticulum:echobot
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - echobot-config:/config

  nomadnet:
    hostname: nomadnet
    image: ghcr.io/greymesa/reticulum:nomadnet
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - nomadnet-config:/config

  retipedia:
    hostname: retipedia
    image: ghcr.io/greymesa/reticulum:retipedia
    networks: [reticulum]
    depends_on: [rnsd]
    environment:
      - NODE_NAME: my node name here
      - LXMF_ADDRESS: your LXMF hash here
      - ACCENT_COLOUR: red
      - ZIMS_DIR: /config/storage/zims
    volumes:
      - retipedia-config:/config

  rrcd:
    hostname: rrcd
    image: ghcr.io/greymesa/reticulum:rrcd
    networks: [reticulum]
    depends_on: [rnsd]
    environment:
      RRCD_HUB_NAME:
      ANNOUNCE_INTERVAL: 300
    volumes:
      - rrcd-config:/config

  teapot:
    hostname: teapot
    image: ghcr.io/greymesa/reticulum:teapot
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - teapot-config:/config
    environment:
      ANNOUNCE_NAME: teapot

  rngit:
    hostname: rngit
    image: ghcr.io/greymesa/reticulum:rngit
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - rngit-config:/config
      - rngit-data:/data
    environment:
      ALLOW_ALL_READ: 1
      ALLOW_READ:
      ALLOW_WRITE: 4bbc9219ce924a7d77e00584523c2d4e 2e6bb7b104dce1f3892fa70141760f68
      ANNOUNCE_INTERVAL: 300
      ANNOUNCE_NAME:

  retibbs:
    hostname: retibbs
    image: ghcr.io/greymesa/reticulum:retibbs
    networks: [reticulum]
    depends_on: [rnsd]
    volumes:
      - retibbs-config:/config
      - retibbs-data:/data

volumes:
  rnsd-config:
  lxmd-config:
  echobot-config:
  nomadnet-config:
  retipedia-config:
  rrcd-config:
  teapot-config:
  rngit-config:
  rngit-data:
  retibbs-config:
  retibbs-data:
networks:
  reticulum:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
